### ISSUE TITLE
Possible to obtain the SnpEff version used in Spritz?

### ISSUE THREAD

**Issue by finnbenned** [smith-chem-wisc/Spritz#190]
Hi,

I am really impressed with your Spritzversion 0.2.2. Here it seems that you are using a special version of SnpEff (info from the vcf file combined.Spritz.sneff.vcf: "SnpEffVersion="4.3u (build 2020-06-25 22:57), by Pablo Cingolani". This outputs an extremely useful and well-structured fasta file with e.g. variants in a protein fasta being combined but dependent on whether such variants are homo- or heterozygous - very neat!

Would it be possible to obtain this SnpEff build which appears quite different from the available 4.3u version the GitHub SNpEff site?

Best, Finn

**Comment by trishorts** [comment]
Thanks for your question. We will try to respond soon.

**Comment by acesnik** [comment]
Great to hear! Yes, the customized version of of SnpEff is publicly available here: https://github.com/smith-chem-wisc/SnpEff

**Comment by acesnik** [comment]
And this is the current release of that fork: https://github.com/smith-chem-wisc/SnpEff/releases/tag/4.3_SCW1

**Comment by acesnik** [comment]
I should also clarify that the combinatorics regarding homo- and heterozygous variants is part of this Spritz module: https://github.com/smith-chem-wisc/Spritz/tree/master/Spritz/TransferUniProtModifications. The fasta file output by Spritz does not have variants applied with any combinatorics.

**Comment by acesnik** [comment]
(I edited my previous comment: the fasta output by SnpEff (not Spritz) does not have variants applied with combinatorics.)

**Comment by acesnik** [comment]
Hi Finn,

I hope this answered your question about the Spritz's custom SnpEff version and the subsequent Spritz scripts.

I also wanted to update you that we released Spritz 0.2.3 with some improvements to the types of inputs that can be used. Single-end RNA-Seq data and mixed input data types can now be used. 

Spritz was also accepted for publication at J. Proteome Res. since August, which you can find here if that is of interest: https://pubs.acs.org/doi/abs/10.1021/acs.jproteome.0c00407.

Best regards,

Anthony
